# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 366)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoWidget = QVideoWidget(self.centralWidget)
        self.videoWidget.setObjectName("videoWidget")
        self.verticalLayout.addWidget(self.videoWidget)
        self.frameButtons = QtWidgets.QFrame(self.centralWidget)
        self.frameButtons.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frameButtons.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOpen = QtWidgets.QPushButton(self.frameButtons)
        self.btnOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/001.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpen.setIcon(icon)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnPlay = QtWidgets.QPushButton(self.frameButtons)
        self.btnPlay.setEnabled(False)
        self.btnPlay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/620.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon1)
        self.btnPlay.setObjectName("btnPlay")
        self.horizontalLayout.addWidget(self.btnPlay)
        self.btnPause = QtWidgets.QPushButton(self.frameButtons)
        self.btnPause.setEnabled(False)
        self.btnPause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/622.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPause.setIcon(icon2)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout.addWidget(self.btnPause)
        self.btnStop = QtWidgets.QPushButton(self.frameButtons)
        self.btnStop.setEnabled(False)
        self.btnStop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/624.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon3)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        spacerItem = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSound = QtWidgets.QPushButton(self.frameButtons)
        self.btnSound.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/volumn.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSound.setIcon(icon4)
        self.btnSound.setFlat(True)
        self.btnSound.setObjectName("btnSound")
        self.horizontalLayout.addWidget(self.btnSound)
        self.sliderVolumn = QtWidgets.QSlider(self.frameButtons)
        self.sliderVolumn.setMaximum(100)
        self.sliderVolumn.setProperty("value", 100)
        self.sliderVolumn.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolumn.setObjectName("sliderVolumn")
        self.horizontalLayout.addWidget(self.sliderVolumn)
        self.btnFullScreen = QtWidgets.QPushButton(self.frameButtons)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/237.GIF"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFullScreen.setIcon(icon5)
        self.btnFullScreen.setObjectName("btnFullScreen")
        self.horizontalLayout.addWidget(self.btnFullScreen)
        self.btnClose = QtWidgets.QPushButton(self.frameButtons)
        self.btnClose.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/132.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon6)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.frameButtons)
        self.frameProgress = QtWidgets.QFrame(self.centralWidget)
        self.frameProgress.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frameProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProgress.setObjectName("frameProgress")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameProgress)
        self.horizontalLayout_2.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabCurMedia = QtWidgets.QLabel(self.frameProgress)
        self.LabCurMedia.setMinimumSize(QtCore.QSize(100, 0))
        self.LabCurMedia.setObjectName("LabCurMedia")
        self.horizontalLayout_2.addWidget(self.LabCurMedia)
        self.sliderPosition = QtWidgets.QSlider(self.frameProgress)
        self.sliderPosition.setTracking(False)
        self.sliderPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPosition.setObjectName("sliderPosition")
        self.horizontalLayout_2.addWidget(self.sliderPosition)
        self.LabRatio = QtWidgets.QLabel(self.frameProgress)
        self.LabRatio.setMinimumSize(QtCore.QSize(80, 0))
        self.LabRatio.setObjectName("LabRatio")
        self.horizontalLayout_2.addWidget(self.LabRatio)
        self.verticalLayout.addWidget(self.frameProgress)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.end_point_value = QtWidgets.QSlider(self.centralWidget)
        self.end_point_value.setOrientation(QtCore.Qt.Horizontal)
        self.end_point_value.setObjectName("end_point_value")
        self.end_point_value.setMinimum(0)
        self.end_point_value.setMaximum(1000)
        self.gridLayout.addWidget(self.end_point_value, 1, 2, 1, 1)
        self.start_point = QtWidgets.QLabel(self.centralWidget)
        self.start_point.setObjectName("start_point")
        self.gridLayout.addWidget(self.start_point, 0, 0, 1, 1)
        self.end_point = QtWidgets.QLabel(self.centralWidget)
        self.end_point.setObjectName("end_point")
        self.gridLayout.addWidget(self.end_point, 1, 0, 1, 1)
        self.start_point_value = QtWidgets.QSlider(self.centralWidget)
        self.start_point_value.setOrientation(QtCore.Qt.Horizontal)
        self.start_point_value.setObjectName("start_point_value")
        self.start_point_value.setMinimum(0)
        self.start_point_value.setMaximum(1000)
        self.gridLayout.addWidget(self.start_point_value, 0, 2, 1, 1)
        self.start_time_display = QtWidgets.QLabel(self.centralWidget)
        self.start_time_display.setObjectName("start_time_display")
        self.gridLayout.addWidget(self.start_time_display, 0, 1, 1, 1)
        self.end_time_display = QtWidgets.QLabel(self.centralWidget)
        self.end_time_display.setObjectName("end_time_display")
        self.gridLayout.addWidget(self.end_time_display, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.start_processing = QtWidgets.QPushButton(self.centralWidget)
        self.start_processing.setObjectName("start_processing")
        self.verticalLayout.addWidget(self.start_processing)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.btnClose.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo10_5，视频播放器"))
        self.btnOpen.setToolTip(_translate("MainWindow", "打开文件"))
        self.btnPlay.setToolTip(_translate("MainWindow", "播放"))
        self.btnPause.setToolTip(_translate("MainWindow", "暂停"))
        self.btnStop.setToolTip(_translate("MainWindow", "停止"))
        self.btnFullScreen.setToolTip(_translate("MainWindow", "全屏播放"))
        self.btnFullScreen.setText(_translate("MainWindow", "全屏"))
        self.btnClose.setToolTip(_translate("MainWindow", "退出"))
        self.LabCurMedia.setText(_translate("MainWindow", "文件名"))
        self.LabRatio.setText(_translate("MainWindow", "进度"))
        self.start_point.setText(_translate("MainWindow", "开始时间"))
        self.end_point.setText(_translate("MainWindow", "结束时间"))
        self.start_time_display.setText(_translate("MainWindow", "--:--"))
        self.end_time_display.setText(_translate("MainWindow", "--:--"))
        self.start_processing.setText(_translate("MainWindow", "开始处理"))
        

from PyQt5.QtMultimediaWidgets import QVideoWidget
import res_rc
